[profile.default]
src = "contracts/production"
test = "test/v1"
script = "script/v1"
out = "out-v1"
cache_path = "cache-v1"
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 1
via_ir = true
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
fs_permissions = [
    { access = "read-write", path = "./deployments" }
]

[fuzz]
runs = 5000

[invariant]
runs = 1000
depth = 64
fail_on_revert = false
