(() => {
  'use strict';
  if (!document.body?.classList.contains('studio-page-body')) return;

  const $ = id => document.getElementById(id);
  const CHAIN_ID = 11155111;
  const ZERO = '0x' + '0'.repeat(64);
  const FACTORY_ABI = [
    'function isRelicForgeCollection(address) view returns(bool)',
    'function dataForCollection(address) view returns(address)',
    'function mintPhasesForCollection(address) view returns(address)',
    'function creatorCollectionCount(address) view returns(uint256)',
    'function creatorCollectionAt(address,uint256) view returns(address)'
  ];
  const COLLECTION_ABI = [
    'function name() view returns(string)','function symbol() view returns(string)','function description() view returns(string)',
    'function creator() view returns(address)','function controller() view returns(address)','function dataContract() view returns(address)','function mintPhases() view returns(address)',
    'function payoutReceiver() view returns(address)','function royaltyReceiver() view returns(address)','function royaltyBps() view returns(uint96)',
    'function maxSupply() view returns(uint32)','function futureRevealMode() view returns(uint8)','function platformFeeMode() view returns(uint8)',
    'function batchWindowSeconds() view returns(uint64)','function maxRandomnessCostPerBatchWei() view returns(uint256)',
    'function flattenedRenderBaseURI() view returns(string)','function holderRenderModeEnabled() view returns(bool)','function defaultRenderMode() view returns(uint8)',
    'function setRenderConfig(string,bool,uint8)'
  ];
  const DATA_ABI = [
    'function creator() view returns(address)','function maxSupply() view returns(uint32)','function canvasWidth() view returns(uint16)','function canvasHeight() view returns(uint16)','function layerCount() view returns(uint8)',
    'function oneOfOneLayerPlusOne() view returns(uint8)','function contentSealed() view returns(bool)','function provenanceHash() view returns(bytes32)',
    'function recipeCount() view returns(uint32)','function recipesPerShard() view returns(uint16)','function validatedRecipeCursor() view returns(uint64)','function placeholderShard() view returns(address)',
    'function artShards(uint256) view returns(address)','function dnaShards(uint256) view returns(address)','function layerNames(uint8) view returns(string)','function layerHiddenFromMetadata(uint8) view returns(bool)',
    'function traitDetails(uint8,uint8) view returns(string,address,uint32,uint32,uint8,bool,bool)',
    'function oneOfOneMetadata(uint8) view returns(string,string,bool)','function oneOfOneAttributeCount(uint8) view returns(uint16)','function oneOfOneAttribute(uint8,uint16) view returns(string,string)',
    'function readPlaceholder() view returns(bytes)',
    'function addArtShard(bytes) returns(address)','function addDnaShard(bytes) returns(address)','function setLayerNames(string[])','function setLayerMetadataVisibility(bool[])','function setOneOfOneLayer(uint8)',
    'function addTraits(tuple(uint8 layer,uint8 index,string name,address shard,uint32 offset,uint32 length,uint8 encoding,bool hiddenFromMetadata)[])',
    'function setDNAConfig(uint32,uint16)','function setPlaceholder(bytes)','function setOneOfOneMetadata(uint8,string,string,string[],string[])','function validateNextRecipes(uint32)','function sealContent(bytes32)'
  ];
  const PHASES_ABI = [
    'function controller() view returns(address)','function phaseCount() view returns(uint32)','function masterMintEnabled() view returns(bool)',
    'function phases(uint32) view returns(uint96 price,uint64 startTime,uint64 endTime,uint32 phaseSupply,uint32 minted,uint32 maxPerWallet,bytes32 merkleRoot,uint8 accessType,uint16 priority,bool enabled)',
    'function createPhase(uint96,uint64,uint64,uint32,uint32,bytes32,uint8,uint16,bool) returns(uint32)','function setMasterMintEnabled(bool)'
  ];

  const ui = { steps: [], busy: false, saveTimer: null, recoveryJournal: null };
  function api(){ if(!window.RelicForgeForge?.getResumeContext) throw new Error('Resumable deployment API is unavailable. Reload Studio.'); return window.RelicForgeForge; }
  function esc(v){ return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function short(v){ const s=String(v||''); return s.length>14?`${s.slice(0,6)}…${s.slice(-4)}`:s; }
  function sameAddr(a,b){ try{return window.ethers.getAddress(a).toLowerCase()===window.ethers.getAddress(b).toLowerCase();}catch{return false;} }
  function asHex(v){ return window.ethers.hexlify(v).toLowerCase(); }
  function shardCode(v){ return ('0xfe'+asHex(v).slice(2)).toLowerCase(); }
  function schedule(v,label){ const raw=String(v||'').trim(); if(!raw)return 0; const d=new Date(raw); if(!Number.isFinite(d.getTime()))throw new Error(`${label} is invalid.`); return Math.floor(d.getTime()/1000); }
  function setStatus(msg,tone=''){ const n=$('r24ResumeStatus'); if(n){n.textContent=msg;n.className=`r24-status ${tone}`.trim();} }
  function step(key,label,state='pending',detail=''){ let r=ui.steps.find(x=>x.key===key); if(!r){r={key,label,state,detail};ui.steps.push(r);} else Object.assign(r,{label,state,detail}); renderSteps(); }
  function renderSteps(){ const n=$('r24ResumeSteps'); if(!n)return; if(!ui.steps.length){n.innerHTML='<div class="r24-empty">No deployment inspection has been run yet.</div>';return;} n.innerHTML=ui.steps.map(r=>`<div class="r24-step ${esc(r.state)}"><span class="r24-dot"></span><div><strong>${esc(r.label)}</strong>${r.detail?`<small>${esc(r.detail)}</small>`:''}</div><b>${r.state==='done'?'CONFIRMED':r.state==='active'?'RUNNING':r.state==='blocked'?'BLOCKED':'PENDING'}</b></div>`).join(''); }
  function journalLabel(s){ return ({creating:'Creating collection',partial:'Interrupted','base-complete':'Base deployment complete','onchain-complete':'Onchain complete','proof-sync-pending':'Proof sync pending',complete:'Launch complete'})[s]||s||'No journal'; }
  function updateJournal(j){ if($('r24ResumeBadge'))$('r24ResumeBadge').textContent=journalLabel(j?.status); if($('r24ResumeAddress'))$('r24ResumeAddress').textContent=j?.collectionAddress?short(j.collectionAddress):'No collection bound'; if($('r24ResumeFingerprint'))$('r24ResumeFingerprint').textContent=j?.provenance?`${j.provenance.slice(0,12)}…`:'Compile to generate fingerprint'; }
  function autoSave(){ clearTimeout(ui.saveTimer); ui.saveTimer=setTimeout(()=>{const b=$('saveProjectBtn'); if(b&&!b.disabled)b.click();},650); }

  function installPanel(){
    if($('r24ResumePanel'))return;
    const anchor=$('forgeCompiledSummary'); if(!anchor)return;
    const panel=document.createElement('section'); panel.id='r24ResumePanel'; panel.className='r24-resume-panel';
    panel.innerHTML=`<div class="r24-head"><div><span>DEPLOYMENT RECOVERY</span><h4>Resumable R12-v2 deployment</h4><p>Relic Forge checks Sepolia first and submits only missing deployment steps. Confirmed transactions are never blindly replayed.</p></div><b id="r24ResumeBadge">No journal</b></div><div class="r24-meta"><div><span>Collection</span><code id="r24ResumeAddress">No collection bound</code></div><div><span>Build fingerprint</span><code id="r24ResumeFingerprint">Compile to generate fingerprint</code></div></div><div class="r24-actions"><button class="ghost-btn" id="r24CheckDeploymentBtn" type="button">Check Deployment Status</button><button class="primary-btn" id="r24ResumeDeploymentBtn" type="button">Resume Deployment</button></div><div class="r24-status" id="r24ResumeStatus">No interrupted deployment detected yet.</div><div class="r24-step-list" id="r24ResumeSteps"></div>`;
    anchor.insertAdjacentElement('afterend',panel);
    $('r24CheckDeploymentBtn').addEventListener('click',()=>run(false).catch(fail));
    $('r24ResumeDeploymentBtn').addEventListener('click',()=>run(true).catch(fail));
    updateJournal(api().getDeploymentJournal?.());
  }
  function fail(error){ console.error('Resume deployment:',error); setStatus(`Resume: ${error.shortMessage||error.message}`,'bad'); ui.busy=false; const b=$('r24ResumeDeploymentBtn'); if(b){b.disabled=false;b.textContent='Resume Deployment';} }

  async function context(){
    const launchScope=await window.RelicForgeForgeNetwork.requireReady();
    if(launchScope.chainId!==11155111)throw new Error('Mainnet deployment recovery remains locked until R3D-B recovery certification.');
    let c=api().getResumeContext();
    if(!c.compiled){ setStatus('Compiling the current Step 4 build so the immutable fingerprint can be verified…','warn'); await api().compileForOnchain(); c=api().getResumeContext(); }
    if(!c.compiled)throw new Error('Compile for Onchain did not produce a valid package.');
    if(!c.signer||!c.wallet){ await api().connectWallet(); c=api().getResumeContext(); }
    if(!c.signer||!c.wallet)throw new Error('Connect the creator wallet.');
    const network=await c.provider.getNetwork(); if(Number(network.chainId)!==CHAIN_ID)throw new Error('Switch the creator wallet to Sepolia.');
    return c;
  }
  function launchInputs(ctx){
    const s=ctx.projectState;
    const payout=String(s.payoutWallet||'').trim()||ctx.wallet, royalty=String(s.royaltyWallet||'').trim()||ctx.wallet;
    const publicStart=schedule(s.publicMintStart,'Public start'), publicEnd=schedule(s.publicMintEnd,'Public end'); if(publicEnd&&publicEnd<=publicStart)throw new Error('Public end must be later than public start.');
    let allowlists=(window.RelicForgeStudioR13?.getAllowlistPhases?.()||[]).filter(x=>x.enabled!==false&&x.whitelist?.entries?.length);
    if(!allowlists.length&&s.whitelistEnabled&&s.whitelist?.entries?.length)allowlists=[{id:'legacy-primary',name:'Allowlist 1',mintPrice:s.whitelistMintPrice||'0',start:s.whitelistMintStart||'',end:s.whitelistMintEnd||'',whitelist:s.whitelist}];
    return { payout,royalty,royaltyBps:Math.round(Number(s.royalty||0)*100),publicEnabled:!!s.publicMintEnabled,publicPrice:window.ethers.parseEther(String(Math.max(0,Number(s.mintPrice||0)))),publicStart,publicEnd,maxPerWallet:Math.max(0,Math.floor(Number(s.maxPerWallet||0))),feeMode:Number(s.platformFeeMode||2),revealMode:Number(s.revealMode||0),batchWindow:Number(s.batchWindowSeconds||180),ceiling:window.ethers.parseEther(String(s.maxRandomnessCostPerBatchEth||'0.02')),holderRender:!!s.holderRenderModeEnabled,defaultRender:Number(s.defaultRenderMode||0),allowlists };
  }
  function pair(a,b){ if(!b)return a; return BigInt(a)<=BigInt(b)?window.ethers.keccak256(window.ethers.concat([a,b])):window.ethers.keccak256(window.ethers.concat([b,a])); }
  function merkle(entries,collection,phaseId){
    const clean=(entries||[]).map(r=>({address:window.ethers.getAddress(String(r.address||'').toLowerCase()),allowance:Number(r.allowance)})); if(!clean.length)throw new Error('Approved Wallet stage has no wallets.');
    const coder=window.ethers.AbiCoder.defaultAbiCoder(); const leaves=clean.map(r=>window.ethers.keccak256(coder.encode(['uint256','address','uint32','address','uint32'],[BigInt(CHAIN_ID),collection,Number(phaseId),r.address,r.allowance]))); const layers=[leaves];
    while(layers.at(-1).length>1){const p=layers.at(-1),next=[];for(let i=0;i<p.length;i+=2)next.push(i+1<p.length?pair(p[i],p[i+1]):p[i]);layers.push(next);} const proofByAddress={};
    clean.forEach((r,index)=>{const proof=[];let cursor=index;for(let level=0;level<layers.length-1;level++){const sibling=cursor^1;if(sibling<layers[level].length)proof.push(layers[level][sibling]);cursor=Math.floor(cursor/2);}proofByAddress[r.address.toLowerCase()]={allowance:r.allowance,proof};});
    return {root:layers.at(-1)[0],entries:clean,proofByAddress};
  }

  async function checkCandidate(address,ctx,compiled,input,deep=false){
    const factory=new window.ethers.Contract(ctx.config.factory,FACTORY_ABI,ctx.provider); if(!await factory.isRelicForgeCollection(address))return null;
    const dataAddress=window.ethers.getAddress(await factory.dataForCollection(address)), mintPhasesAddress=window.ethers.getAddress(await factory.mintPhasesForCollection(address));
    const collection=new window.ethers.Contract(address,COLLECTION_ABI,ctx.provider), data=new window.ethers.Contract(dataAddress,DATA_ABI,ctx.provider);
    const vals=await Promise.all([collection.name(),collection.symbol(),collection.description(),collection.creator(),collection.controller(),collection.dataContract(),collection.mintPhases(),collection.payoutReceiver(),collection.royaltyReceiver(),collection.royaltyBps(),collection.maxSupply(),collection.futureRevealMode(),collection.platformFeeMode(),collection.batchWindowSeconds(),collection.maxRandomnessCostPerBatchWei(),data.creator(),data.maxSupply(),data.canvasWidth(),data.canvasHeight(),data.layerCount(),data.contentSealed(),data.provenanceHash()]);
    const [name,symbol,description,creator,controller,boundData,boundPhases,payout,royalty,royaltyBps,maxSupply,revealMode,feeMode,batchWindow,ceiling,dataCreator,dataSupply,width,height,layerCount,sealed,provenance]=vals; const bad=[];
    if(name!==compiled.core.name)bad.push('name'); if(symbol!==compiled.core.symbol)bad.push('symbol'); if(description!==compiled.core.description)bad.push('description'); if(!sameAddr(creator,ctx.wallet))bad.push('creator'); if(!sameAddr(boundData,dataAddress)||!sameAddr(boundPhases,mintPhasesAddress))bad.push('contract bindings'); if(Number(maxSupply)!==compiled.recipeCount||Number(dataSupply)!==compiled.recipeCount)bad.push('supply'); if(Number(width)!==compiled.core.canvas[0]||Number(height)!==compiled.core.canvas[1]||Number(layerCount)!==compiled.layerDefs.length)bad.push('canvas/layers'); if(!sameAddr(dataCreator,ctx.wallet))bad.push('ProjectData creator'); if(Number(revealMode)!==input.revealMode)bad.push('reveal'); if(Number(feeMode)!==input.feeMode)bad.push('fee mode'); if(Number(batchWindow)!==input.batchWindow)bad.push('batch window'); if(BigInt(ceiling)!==BigInt(input.ceiling))bad.push('randomness ceiling'); if(!sameAddr(payout,input.payout)||!sameAddr(royalty,input.royalty)||Number(royaltyBps)!==input.royaltyBps)bad.push('payout/royalty'); if(Boolean(sealed)&&String(provenance).toLowerCase()!==compiled.provenance.toLowerCase())bad.push('sealed provenance');
    if(bad.length)return {address,dataAddress,mintPhasesAddress,bad,sealed:Boolean(sealed)};
    if(deep&&!sealed){await verifyShardPrefix(data,ctx.provider,compiled.artShards,'artShards','Artwork');await verifyShardPrefix(data,ctx.provider,compiled.dnaShards,'dnaShards','DNA');}
    return {address:window.ethers.getAddress(address),dataAddress,mintPhasesAddress,sealed:Boolean(sealed),controller:window.ethers.getAddress(controller)};
  }
  async function verifyShardPrefix(data,provider,expected,getter,label){ for(let i=0;i<expected.length;i++){let p;try{p=await data[getter](i);}catch{return;}if((await provider.getCode(p)).toLowerCase()!==shardCode(expected[i]))throw new Error(`${label} shard ${i+1} does not match this compiled build.`);} }
  async function resolve(ctx,compiled,input){
    const addresses=[]; const add=a=>{if(a&&window.ethers.isAddress(a)&&!addresses.some(x=>x.toLowerCase()===a.toLowerCase()))addresses.push(window.ethers.getAddress(a));}; add(ctx.collectionAddress);add(ctx.journal?.collectionAddress);add(api().findLocalDeploymentJournal?.(compiled.provenance)?.collectionAddress);
    for(const a of addresses){const s=await checkCandidate(a,ctx,compiled,input,true);if(s&&!s.bad?.length)return s;}
    const factory=new window.ethers.Contract(ctx.config.factory,FACTORY_ABI,ctx.provider), count=Number(await factory.creatorCollectionCount(ctx.wallet)), matches=[];
    for(let i=count-1;i>=Math.max(0,count-25);i--){try{const a=await factory.creatorCollectionAt(ctx.wallet,i),s=await checkCandidate(a,ctx,compiled,input,true);if(s&&!s.bad?.length)matches.push(s);}catch{}}
    if(matches.length===1)return matches[0]; if(matches.length>1)throw new Error(`Multiple matching partial collections were found (${matches.map(x=>short(x.address)).join(', ')}). Reopen the saved project containing the intended address.`); throw new Error('No matching partial deployment was found for this build and creator wallet.');
  }
  /* R3D-B2 R2 durable resume transaction: exact intent is checkpointed before wallet submission. */
  function plan(contract,method,args,verify){return {contract,method,args,verify};}
  async function tx(label,key,transactionPlan,ctx){
    if(!ui.recoveryJournal)throw new Error('Scoped recovery journal is unavailable. Re-check the deployment before resuming.');
    step(key,label,'active','Preparing durable transaction intent');
    await api().requireForgeWrite(true);
    const result=await window.RF26Recovery.executeIntent({
      journal:ui.recoveryJournal,stepKey:key,label,
      contract:transactionPlan.contract,method:transactionPlan.method,args:transactionPlan.args,
      verify:transactionPlan.verify
    });
    ui.recoveryJournal=result.journal;
    const txHash=result.transactionHash||result.receipt?.hash;
    if(txHash)api().checkpointExternalDeployment?.(key,txHash,label);
    step(key,label,'done',txHash?short(txHash)+' · intent + state verified':'Intent + state verified');
  }

  async function reconcileData(ctx,snap,c,input,mutate){
    const data=new window.ethers.Contract(snap.dataAddress,DATA_ABI,mutate?ctx.signer:ctx.provider), collection=new window.ethers.Contract(snap.address,COLLECTION_ABI,mutate?ctx.signer:ctx.provider);
    if(snap.sealed){const p=await data.provenanceHash();if(String(p).toLowerCase()!==c.provenance.toLowerCase())throw new Error('Sealed provenance does not match this build.');step('seal','Immutable content sealed','done','Provenance matches');return;}
    const art=[];
    for(let i=0;i<c.artShards.length;i++){let p=null;try{p=await data.artShards(i);}catch{} const key=`art-${i}`; if(p){if((await ctx.provider.getCode(p)).toLowerCase()!==shardCode(c.artShards[i]))throw new Error(`Artwork shard ${i+1} conflicts with this build.`);art[i]=p;step(key,`Artwork shard ${i+1}/${c.artShards.length}`,'done','Exact bytes');}else if(!mutate)step(key,`Artwork shard ${i+1}/${c.artShards.length}`,'pending','Missing');else{await tx(`Write artwork shard ${i+1}/${c.artShards.length}`,key,plan(data,'addArtShard',[asHex(c.artShards[i])],async()=>{const p=await data.artShards(i);if(!p||(await ctx.provider.getCode(p)).toLowerCase()!==shardCode(c.artShards[i]))throw new Error(`Artwork shard ${i+1} postcondition failed.`);}),ctx);art[i]=await data.artShards(i);}}
    try{const extra=await data.artShards(c.artShards.length);if(extra)throw new Error('Unexpected extra artwork shard.');}catch(e){if(/Unexpected/.test(e.message))throw e;}
    const names=await Promise.all(c.layerDefs.map((_,i)=>data.layerNames(i))), expectedNames=c.layerDefs.map(x=>x.name); if(names.some((v,i)=>v&&v!==expectedNames[i]))throw new Error('Onchain layer names conflict with this build.'); if(names.every((v,i)=>v===expectedNames[i]))step('layers','Layer names','done','Matches');else if(!mutate)step('layers','Layer names','pending','Missing');else await tx('Register layer names','layers',plan(data,'setLayerNames',[expectedNames],async()=>{const now=await Promise.all(c.layerDefs.map((_,i)=>data.layerNames(i)));if(now.some((v,i)=>v!==expectedNames[i]))throw new Error('Layer-name postcondition failed.');}),ctx);
    const hidden=await Promise.all(c.layerDefs.map((_,i)=>data.layerHiddenFromMetadata(i))), expHidden=c.layerDefs.map(x=>!!x.metadataHidden); if(hidden.some((v,i)=>v===true&&expHidden[i]===false))throw new Error('Metadata visibility conflicts with this build.'); if(hidden.every((v,i)=>Boolean(v)===expHidden[i]))step('visibility','Metadata visibility','done','Matches');else if(!mutate)step('visibility','Metadata visibility','pending','Missing');else await tx('Configure metadata visibility','visibility',plan(data,'setLayerMetadataVisibility',[expHidden],async()=>{const now=await Promise.all(c.layerDefs.map((_,i)=>data.layerHiddenFromMetadata(i)));if(now.some((v,i)=>Boolean(v)!==expHidden[i]))throw new Error('Metadata-visibility postcondition failed.');}),ctx);
    if(c.oneOfOneLayerIndex>=0){const cur=Number(await data.oneOfOneLayerPlusOne()),exp=c.oneOfOneLayerIndex+1;if(cur&&cur!==exp)throw new Error('1/1 layer conflicts with this build.');if(cur===exp)step('one-layer','1/1 layer','done','Matches');else if(!mutate)step('one-layer','1/1 layer','pending','Missing');else await tx('Configure standalone 1/1 layer','one-layer',plan(data,'setOneOfOneLayer',[c.oneOfOneLayerIndex],async()=>{if(Number(await data.oneOfOneLayerPlusOne())!==c.oneOfOneLayerIndex+1)throw new Error('1/1 layer postcondition failed.');}),ctx);}
    for(let i=0;i<(c.oneOfOneMetadataInputs||[]).length;i++){const row=c.oneOfOneMetadataInputs[i],cur=await data.oneOfOneMetadata(row[0]),exists=Boolean(cur.exists??cur[2]),key=`one-meta-${i}`;let attrs=[];try{attrs=row[3]?JSON.parse(row[3]):[];}catch{throw new Error('Compiled 1/1 metadata is invalid.');}if(exists){if(String(cur.tokenName??cur[0])!==String(row[1])||String(cur.tokenDescription??cur[1])!==String(row[2]))throw new Error(`1/1 metadata ${i+1} conflicts.`);const count=Number(await data.oneOfOneAttributeCount(row[0]));if(count!==attrs.length)throw new Error(`1/1 metadata ${i+1} attributes conflict.`);step(key,`1/1 metadata ${i+1}`,'done','Matches');}else if(!mutate)step(key,`1/1 metadata ${i+1}`,'pending','Missing');else await tx(`Store 1/1 metadata ${i+1}`,key,plan(data,'setOneOfOneMetadata',[row[0],row[1],row[2],attrs.map(x=>String(x.trait_type)),attrs.map(x=>String(x.value))],async()=>{const now=await data.oneOfOneMetadata(row[0]);if(!Boolean(now.exists??now[2])||String(now.tokenName??now[0])!==String(row[1])||String(now.tokenDescription??now[1])!==String(row[2]))throw new Error(`1/1 metadata ${i+1} postcondition failed.`);const count=Number(await data.oneOfOneAttributeCount(row[0]));if(count!==attrs.length)throw new Error(`1/1 metadata ${i+1} attribute postcondition failed.`);for(let a=0;a<attrs.length;a++){const got=await data.oneOfOneAttribute(row[0],a);if(String(got[0])!==String(attrs[a].trait_type)||String(got[1])!==String(attrs[a].value))throw new Error(`1/1 metadata ${i+1} attribute ${a+1} postcondition failed.`);}}),ctx);}
    const batches=Math.ceil(c.traits.length/30);for(let start=0,b=1;start<c.traits.length;start+=30,b++){const items=c.traits.slice(start,start+30),key=`traits-${b}`;let missing=false;for(const t of items){const cur=await data.traitDetails(t.layerIndex,t.traitIndex),exists=Boolean(cur.exists??cur[6]);if(!exists){missing=true;continue;}const p=art[Number(t.shard)]||await data.artShards(Number(t.shard));if(String(cur.traitName??cur[0])!==String(t.name)||!sameAddr(cur.shard??cur[1],p)||Number(cur.offset??cur[2])!==Number(t.offset)||Number(cur.length??cur[3])!==Number(t.length)||Number(cur.encoding??cur[4])!==Number(t.encodingCode)||Boolean(cur.hiddenFromMetadata??cur[5])!==Boolean(t.metadataHidden))throw new Error(`Trait ${t.layerName} / ${t.name} conflicts with this build.`);}if(!missing)step(key,`Trait batch ${b}/${batches}`,'done','Matches');else if(!mutate)step(key,`Trait batch ${b}/${batches}`,'pending','Missing');else await tx(`Register trait batch ${b}/${batches}`,key,plan(data,'addTraits',[items.map(t=>[t.layerIndex,t.traitIndex,t.name,art[Number(t.shard)],t.offset,t.length,t.encodingCode,!!t.metadataHidden])],async()=>{for(const t of items){const now=await data.traitDetails(t.layerIndex,t.traitIndex),p=art[Number(t.shard)]||await data.artShards(Number(t.shard));if(!Boolean(now.exists??now[6])||String(now.traitName??now[0])!==String(t.name)||!sameAddr(now.shard??now[1],p)||Number(now.offset??now[2])!==Number(t.offset)||Number(now.length??now[3])!==Number(t.length)||Number(now.encoding??now[4])!==Number(t.encodingCode)||Boolean(now.hiddenFromMetadata??now[5])!==Boolean(t.metadataHidden))throw new Error(`Trait ${t.layerName} / ${t.name} postcondition failed.`);}}),ctx);}
    for(let i=0;i<c.dnaShards.length;i++){let p=null;try{p=await data.dnaShards(i);}catch{}const key=`dna-${i}`;if(p){if((await ctx.provider.getCode(p)).toLowerCase()!==shardCode(c.dnaShards[i]))throw new Error(`DNA shard ${i+1} conflicts.`);step(key,`DNA shard ${i+1}/${c.dnaShards.length}`,'done','Exact bytes');}else if(!mutate)step(key,`DNA shard ${i+1}/${c.dnaShards.length}`,'pending','Missing');else await tx(`Write DNA shard ${i+1}/${c.dnaShards.length}`,key,plan(data,'addDnaShard',[asHex(c.dnaShards[i])],async()=>{const p=await data.dnaShards(i);if(!p||(await ctx.provider.getCode(p)).toLowerCase()!==shardCode(c.dnaShards[i]))throw new Error(`DNA shard ${i+1} postcondition failed.`);}),ctx);}
    try{const extra=await data.dnaShards(c.dnaShards.length);if(extra)throw new Error('Unexpected extra DNA shard.');}catch(e){if(/Unexpected/.test(e.message))throw e;}
    const rc=Number(await data.recipeCount()),rps=Number(await data.recipesPerShard());if(rc===c.recipeCount&&rps===c.recipesPerShard)step('dna-config','DNA configuration','done','Matches');else if(rc||rps)throw new Error('DNA configuration conflicts with this build.');else if(!mutate)step('dna-config','DNA configuration','pending','Missing');else await tx('Configure DNA','dna-config',plan(data,'setDNAConfig',[c.recipeCount,c.recipesPerShard],async()=>{if(Number(await data.recipeCount())!==c.recipeCount||Number(await data.recipesPerShard())!==c.recipesPerShard)throw new Error('DNA configuration postcondition failed.');}),ctx);
    const ph=await data.placeholderShard();if(ph!==window.ethers.ZeroAddress){if(String(await data.readPlaceholder()).toLowerCase()!==asHex(c.placeholderBytes))throw new Error('Reveal placeholder conflicts with this build.');step('placeholder','Reveal placeholder','done','Exact bytes');}else if(!mutate)step('placeholder','Reveal placeholder','pending','Missing');else await tx('Store reveal placeholder','placeholder',plan(data,'setPlaceholder',[asHex(c.placeholderBytes)],async()=>{if(String(await data.readPlaceholder()).toLowerCase()!==asHex(c.placeholderBytes))throw new Error('Reveal placeholder postcondition failed.');}),ctx);
    const host=String(window.RELICFORGE_CONFIG?.renderBase||window.RelicForgeCloud?.apiBase?.()||'').replace(/\/$/,''),base=host?`${host}/api/public/render/${CHAIN_ID}/${snap.address}/`:'',holderExpected=input.holderRender&&!!base;const [baseNow,holderNow,modeNow]=await Promise.all([collection.flattenedRenderBaseURI(),collection.holderRenderModeEnabled(),collection.defaultRenderMode()]);if(String(baseNow)===base&&Boolean(holderNow)===holderExpected&&Number(modeNow)===input.defaultRender)step('render','Renderer policy','done','Matches');else if(String(baseNow)&&String(baseNow)!==base)throw new Error('Renderer base URI conflicts with this project.');else if(!mutate)step('render','Renderer policy','pending','Missing');else await tx('Configure renderer policy','render',plan(collection,'setRenderConfig',[base,holderExpected,input.defaultRender],async()=>{const now=await Promise.all([collection.flattenedRenderBaseURI(),collection.holderRenderModeEnabled(),collection.defaultRenderMode()]);if(String(now[0])!==base||Boolean(now[1])!==holderExpected||Number(now[2])!==input.defaultRender)throw new Error('Renderer-policy postcondition failed.');}),ctx);
    let cursor=Number(await data.validatedRecipeCursor());const batchSize=Math.max(1,Math.min(500,Math.floor(4096/c.layerDefs.length)));if(cursor>c.recipeCount)throw new Error('Validation cursor exceeds recipe count.');if(cursor===c.recipeCount)step('validate','Recipe validation','done',`${cursor}/${c.recipeCount}`);else if(!mutate)step('validate','Recipe validation','pending',`${cursor}/${c.recipeCount} confirmed`);else while(cursor<c.recipeCount){const q=Math.min(batchSize,c.recipeCount-cursor);await tx(`Validate recipes ${cursor+1}-${cursor+q}`,'validate',plan(data,'validateNextRecipes',[q],async()=>{if(Number(await data.validatedRecipeCursor())<cursor+q)throw new Error('Recipe-validation postcondition failed.');}),ctx);cursor=Number(await data.validatedRecipeCursor());step('validate','Recipe validation',cursor===c.recipeCount?'done':'active',`${cursor}/${c.recipeCount}`);}
    if(Boolean(await data.contentSealed())){if(String(await data.provenanceHash()).toLowerCase()!==c.provenance.toLowerCase())throw new Error('Sealed provenance conflicts with this build.');step('seal','Seal immutable content','done','Provenance matches');}else if(!mutate)step('seal','Seal immutable content','pending','Ready after missing steps');else await tx('Seal immutable collection content','seal',plan(data,'sealContent',[c.provenance],async()=>{if(!Boolean(await data.contentSealed())||String(await data.provenanceHash()).toLowerCase()!==c.provenance.toLowerCase())throw new Error('Content-seal postcondition failed.');}),ctx);
  }

  function phaseSpec(p,index,collection,id){const start=schedule(p.start,`${p.name||'Allowlist'} start`),end=schedule(p.end,`${p.name||'Allowlist'} end`);if(end&&end<=start)throw new Error(`${p.name||'Allowlist'} end must be later than start.`);const tree=merkle(p.whitelist.entries,collection,id);return{id,name:p.name||`Allowlist ${index+1}`,price:window.ethers.parseEther(String(Math.max(0,Number(p.mintPrice||0)))),start,end,supply:0,maxWallet:0,root:tree.root,access:1,priority:200+index,enabled:true,studioId:p.id};}
  function phaseMatches(r,s){return BigInt(r.price??r[0])===BigInt(s.price)&&Number(r.startTime??r[1])===s.start&&Number(r.endTime??r[2])===s.end&&Number(r.phaseSupply??r[3])===s.supply&&Number(r.maxPerWallet??r[5])===s.maxWallet&&String(r.merkleRoot??r[6]).toLowerCase()===s.root.toLowerCase()&&Number(r.accessType??r[7])===s.access&&Number(r.priority??r[8])===s.priority&&Boolean(r.enabled??r[9])===s.enabled;}
  async function reconcilePhases(ctx,snap,input,mutate){const mp=new window.ethers.Contract(snap.mintPhasesAddress,PHASES_ABI,mutate?ctx.signer:ctx.provider);if(mutate&&!sameAddr(await mp.controller(),ctx.wallet))throw new Error('Connected wallet is not the MintPhases controller.');const specs=[];let id=1,publicPhaseId=null;if(input.publicEnabled){publicPhaseId=id++;specs.push({id:publicPhaseId,name:'Public mint stage',price:input.publicPrice,start:input.publicStart,end:input.publicEnd,supply:0,maxWallet:input.maxPerWallet,root:ZERO,access:0,priority:100,enabled:true});}const bindings=[];input.allowlists.forEach((p,i)=>{const s=phaseSpec(p,i,snap.address,id++);specs.push(s);bindings.push({studioId:p.id,phaseId:s.id,root:s.root});});const count0=Number(await mp.phaseCount());if(count0>specs.length&&!['complete','onchain-complete'].includes(ctx.journal?.status))throw new Error(`MintPhases has ${count0} stages but this interrupted launch expects ${specs.length}. Resume stopped.`);for(const s of specs){const count=Number(await mp.phaseCount()),key=`phase-${s.id}`;if(count>=s.id){const raw=await mp.phases(s.id);if(!phaseMatches(raw,s))throw new Error(`Onchain Stage ${s.id} conflicts with the saved launch.`);step(key,`MintPhases Stage ${s.id} · ${s.name}`,'done','Matches');}else if(count!==s.id-1)throw new Error(`MintPhases sequence is inconsistent at Stage ${s.id}.`);else if(!mutate)step(key,`MintPhases Stage ${s.id} · ${s.name}`,'pending','Missing');else await tx(`Create MintPhases Stage ${s.id} · ${s.name}`,key,plan(mp,'createPhase',[s.price,s.start,s.end,s.supply,s.maxWallet,s.root,s.access,s.priority,s.enabled],async()=>{if(Number(await mp.phaseCount())<s.id||!phaseMatches(await mp.phases(s.id),s))throw new Error(`MintPhases Stage ${s.id} postcondition failed.`);}),ctx);}const primary=input.allowlists[0],schedules=[...(input.publicEnabled?[{start:input.publicStart}]:[]),...(primary?[{start:schedule(primary.start,'Primary allowlist start')}]:[])],autoArm=schedules.length>0&&schedules.every(x=>x.start>0);if(autoArm){if(await mp.masterMintEnabled())step('master','Scheduled minting','done','Already enabled');else if(!mutate)step('master','Scheduled minting','pending','Missing');else await tx('Enable scheduled minting','master',plan(mp,'setMasterMintEnabled',[true],async()=>{if(!Boolean(await mp.masterMintEnabled()))throw new Error('Scheduled-mint postcondition failed.');}),ctx);}api().applyResumeBindings?.({collectionAddress:snap.address,dataAddress:snap.dataAddress,mintPhasesAddress:snap.mintPhasesAddress,publicPhaseId,whitelistPhaseId:bindings[0]?.phaseId||null});const detail=window.RelicForgeStudioR13?.applyResumedPhaseBindings?.(bindings)||window.RelicForgeStudioR13?.getPublicationDetail?.();return detail;}

  async function run(mutate){
    if(ui.busy)return;ui.busy=true;const rf26Leave=window.RelicForgeForgeNetwork.enter();ui.steps=[];renderSteps();const b=$('r24ResumeDeploymentBtn');if(b){b.disabled=true;b.textContent=mutate?'Resuming…':'Resume Deployment';}
    try{let ctx=await context();const c=ctx.compiled,input=launchInputs(ctx);updateJournal(ctx.journal||api().findLocalDeploymentJournal?.(c.provenance));setStatus(mutate?'Reconciling confirmed Sepolia state and resuming only missing steps…':'Checking Sepolia against the compiled build…','warn');const snap=await resolve(ctx,c,input);
      if(mutate){
        if(!window.RF26Recovery?.ensureJournal||!window.RF26Recovery?.executeIntent)throw new Error('R3D-B2 durable recovery runtime is unavailable. Reload Studio.');
        const verified=await window.RF26Recovery.verifyCollection(snap.address,{creator:ctx.wallet,chainId:11155111});
        ui.recoveryJournal=await window.RF26Recovery.ensureJournal({
          provenance:c.provenance,verifiedCollection:verified,legacyJournal:ctx.journal
        });
      }else ui.recoveryJournal=null;
      api().applyResumeBindings?.({collectionAddress:snap.address,dataAddress:snap.dataAddress,mintPhasesAddress:snap.mintPhasesAddress});if(!ctx.journal?.collectionAddress)api().adoptDeploymentJournal?.({provenance:c.provenance,factory:ctx.config.factory,collectionAddress:snap.address,dataAddress:snap.dataAddress,mintPhasesAddress:snap.mintPhasesAddress,status:'partial'});ctx=api().getResumeContext();updateJournal(ctx.journal);step('factory','Collection + ProjectData + MintPhases','done',short(snap.address));if(mutate&&!sameAddr(snap.controller,ctx.wallet))throw new Error('Connected wallet is not the active collection controller.');await reconcileData(ctx,snap,c,input,mutate);const detail=await reconcilePhases(ctx,snap,input,mutate);if(mutate){api().setDeploymentStatus?.('onchain-complete');updateJournal(api().getDeploymentJournal?.());setStatus('All onchain deployment steps are confirmed. Syncing mint-page metadata and Approved Wallet proofs…','good');if(detail)window.dispatchEvent(new CustomEvent('relicforge:v2-launch-complete',{detail}));autoSave();}else{const pending=ui.steps.filter(x=>x.state==='pending').length;setStatus(pending?`${pending} missing deployment step${pending===1?'':'s'} can be resumed safely.`:'No missing onchain deployment steps were found.',pending?'warn':'good');}}
    finally{rf26Leave();ui.busy=false;if(b){b.disabled=false;b.textContent='Resume Deployment';}}
  }

  function refresh(){const j=api().getDeploymentJournal?.();updateJournal(j);if(j?.collectionAddress){if(j.status==='complete')setStatus('Launch complete. Onchain deployment and proof sync are confirmed.','good');else if(j.status==='proof-sync-pending')setStatus('Onchain deployment is complete, but collector proof sync needs attention. Use Repair / Sync Mint Proofs.','warn');else setStatus('An incomplete deployment checkpoint is attached to this project. Check status or Resume Deployment.','warn');}}
  function install(){if(!window.RelicForgeForge?.getResumeContext){setTimeout(install,80);return;}installPanel();refresh();window.addEventListener('relicforge:deployment-checkpoint',e=>{updateJournal(e.detail?.journal);autoSave();refresh();});window.addEventListener('relicforge:v2-proof-sync-complete',()=>{api().setDeploymentStatus?.('complete');updateJournal(api().getDeploymentJournal?.());setStatus('Launch complete. Onchain deployment and Approved Wallet proof sync are confirmed.','good');autoSave();});window.addEventListener('relicforge:v2-proof-sync-failed',e=>{api().setDeploymentStatus?.('proof-sync-pending',e.detail?.error||'Proof sync failed');updateJournal(api().getDeploymentJournal?.());setStatus('Onchain deployment is complete, but collector proof sync needs attention.','warn');autoSave();});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0));else setTimeout(install,0);
})();
